# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('static', models.CharField(max_length=128)),
                ('secret', models.CharField(max_length=128)),
                ('valid', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('responsible', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RoundRobin',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
