# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundrobin',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acta',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='roundrobin',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
