# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitucion', '0002_auto_20160630_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='comuna',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='acta',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
