# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitucion', '0003_auto_20160630_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='person_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='acta',
            name='sheet_row',
            field=models.IntegerField(default=0),
        ),
    ]
