# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitucion', '0004_auto_20160701_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
